### ISSUE TITLE
Server returns 'Request failed with status code 500'

### ISSUE THREAD

**Issue by DGINXREAL** [ionos-deploy-now/ionos-deploy-now#138]
Hello,

i'm unable to setup the project. Every time i clicking on create project button returns a 500 error without reason.

i fetched the id from js response from POST https://api-eu.ionos.space/v4/accounts/me/projects

`Unexpected error occurred: 8c1266e4-679a-45dc-a99a-6c0a34231daf`

![Bildschirmfoto 2024-07-06 um 12 48 41](https://github.com/ionos-deploy-now/ionos-deploy-now/assets/47042042/a3c1c436-6358-4641-a139-96188354ff9a)

**Comment by Ap3rtur3** [comment]
Hello @DGINXREAL,

it looks like there was a secret token `DISCORD_TOKEN `, which could have been exposed as env variable in the generated workflow files and Github tried to prevent that. 

If you have tokens or secrets, which belong in env variables, you can flag them as secret in the setup wizard.
Just click on the incognito icon:

<img width="719" alt="Screenshot at Jul 11 14-51-50" src="https://github.com/ionos-deploy-now/ionos-deploy-now/assets/15201748/1843912a-efba-4f41-a69b-817861cefa67">

Deploy Now will configure the secrets for you in Github and generate a workflow step, which looks like this:

```
- name: Build Node assets
        env:
          CI: true
          PRIVATE_VARIABLE: ${{ secrets.PRIVATE_VARIABLE }}
          PUBLIC_VARIABLE: not secret
          SITE_URL: ${{ inputs.site-url }}
        run: |
          npm install --global yarn
          yarn install --frozen-lockfile
          yarn build
```
