### ISSUE TITLE
.template files don't work

### ISSUE THREAD

**Issue by EzeRangel** [ionos-deploy-now/ionos-deploy-now#39]
Hi 

I've been testing this service with a PHP app and I think the .template files are not being copied.

I'm not sure if this is a bug or I'm missing something, but based in the [docs](https://docs.ionos.space/docs/runtime-configuration) it says I can create a template file inside my `.deploy-now` folder and should be copied after the deployment process.

These are my files in the `.deploy-now` folder.

![Captura de Pantalla 2022-06-24 a la(s) 11 01 30](https://user-images.githubusercontent.com/1395261/175609925-b020f51e-41e6-4899-9269-17d0179ddd56.png)

But I can't see the files in the Deploy Viewer. (The .htaccess I statically put it there.)

![Captura de Pantalla 2022-06-24 a la(s) 11 01 48](https://user-images.githubusercontent.com/1395261/175611773-86fa3a7d-92d3-408d-98c4-1d9df1311ec3.png)

**Comment by EzeRangel** [comment]
In the docs you have this example to render templates

```
 - name: Render templates
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        uses: ionos-deploy-now/template-renderer-action@feature/improvements
```

But there's an error with the version for the action. I changed to `uses: ionos-deploy-now/template-renderer-action@v1` and the process worked as expected.

**Comment by EzeRangel** [comment]
Well after some days of testing I can't make this work. I think my app can't understand what Deploy Now renders as my DB env vars

This is what I see in the Deployment Viewer:
`DATABASE_URL=mysql://@DB_USERNAME@:"@DB_PASSWORD@"@@DB_HOST@:3306/@DB_NAME@` I just don't know if this is correct or if I'm missing something.

**Comment by coder-hugo** [comment]
Hi @EzeRangel ,

I just saw that the example workflow in the docs is incomplete. These placeholders will be replaced by the `deploy-to-ionos-action`. For this the action requires an additional parameter. If you add the following line to the `with` section it should work:
```
runtime-placeholder-files: ${r"${{ steps.template.outputs.runtime-placeholder-files }}"}
```

**Comment by EzeRangel** [comment]
Thanks for the advice @coder-hugo 

I edited my workflow file accordingly but I get the same results, the output for my env files it's still the same.

**Comment by EzeRangel** [comment]
Yes that is the log I see too.

But for some reason, the deploy action ignores the `runtime-placeholder-files` line.


This is my deploy-now.yaml file:
```yaml
# To better understand this file read this:
# https://docs.ionos.space/docs/github-actions-customization/

name: Deploy Now

on:
    - push
    - workflow_dispatch

jobs:
    deploy-now:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Fetch project data
              uses: ionos-deploy-now/retrieve-project-info-action@v1
              id: project
              with:
                  api-key: ${{ secrets.IONOS_API_KEY }}
                  project: ${{ secrets.IONOS_PROJECT_ID }}
                  service-host: api-us.ionos.space

            - name: checkout
              if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
              uses: actions/checkout@v2
              with:
                  submodules: "recursive"

            - name: Setup composer
              if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
              uses: php-actions/composer@v6
              with:
                  php_version: "8.0"
                  version: "2"
                  args: --optimize-autoloader --no-dev

            - name: Render templates
              if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
              uses: ionos-deploy-now/template-renderer-action@v1
              with:
                  secrets: |
                      bolt:
                        secret: ${{ secrets.APP_SECRET }}

            - name: Build PHP assets
              env:
                  APP_ENV: prod
              run: composer dump-env prod --empty

            - name: Deploy to IONOS
              if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
              uses: ionos-deploy-now/deploy-to-ionos-action@v1
              with:
                  project: ${{ secrets.IONOS_PROJECT_ID }}
                  branch-id: ${{ steps.project.outputs.branch-id }}
                  service-host: api-us.ionos.space
                  api-key: ${{ secrets.IONOS_API_KEY }}
                  runtime-placeholder-files: ${{ steps.template.outputs.runtime-placeholder-files }}
                  dist-folder: ./

```
